### ISSUE TITLE
Improve the Styling of the Homepage

### ISSUE THREAD

**Issue by kobasi896** [kobasi896/Infinite-Scrapper#12]
**Issue**: The index.html page can be styled better to look more modern and user-friendly. Simple tasks could include improving the font, padding, and color scheme.
**Task**: Use CSS in styles.css to improve the layout, font selection, and color contrast for better user experience.

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it

**Comment by chidoziemanagwu** [comment]
Please assing to me
